[package]
name = "fend-core"
# Don't forget to update html_root_url and get_version()
version = "0.1.11"
authors = ["printfn <printfn@users.noreply.github.com>"]
description = "Arbitrary-precision unit-aware calculator"
homepage = "https://github.com/printfn/fend"
repository = "https://github.com/printfn/fend"
readme = "README.md"
license = "MIT"
keywords = ["calculator", "library", "conversion", "math", "tool"]
edition = "2018"
categories = ["command-line-utilities", "mathematics", "science"]
exclude = [
    "src/num/gnu-units-original/currency.units",
    "src/num/gnu-units-original/definitions.units"
]

[features]
default = ["gpl"]

# This enables the GNU Units database in `definitions.units` and
# `currency.units`. If disabled, `builtin.units` is used instead.
gpl = []

[dependencies]
